//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	intstr "k8s.io/apimachinery/pkg/util/intstr"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KlusterletVersion) DeepCopyInto(out *KlusterletVersion) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KlusterletVersion.
func (in *KlusterletVersion) DeepCopy() *KlusterletVersion {
	if in == nil {
		return nil
	}
	out := new(KlusterletVersion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KlusterletVersion) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KlusterletVersionList) DeepCopyInto(out *KlusterletVersionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KlusterletVersion, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KlusterletVersionList.
func (in *KlusterletVersionList) DeepCopy() *KlusterletVersionList {
	if in == nil {
		return nil
	}
	out := new(KlusterletVersionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KlusterletVersionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KlusterletVersionSpec) DeepCopyInto(out *KlusterletVersionSpec) {
	*out = *in
	in.RollingConfig.DeepCopyInto(&out.RollingConfig)
	in.RollingCanaryConfig.DeepCopyInto(&out.RollingCanaryConfig)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KlusterletVersionSpec.
func (in *KlusterletVersionSpec) DeepCopy() *KlusterletVersionSpec {
	if in == nil {
		return nil
	}
	out := new(KlusterletVersionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KlusterletVersionStatus) DeepCopyInto(out *KlusterletVersionStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KlusterletVersionStatus.
func (in *KlusterletVersionStatus) DeepCopy() *KlusterletVersionStatus {
	if in == nil {
		return nil
	}
	out := new(KlusterletVersionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlacementRef) DeepCopyInto(out *PlacementRef) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlacementRef.
func (in *PlacementRef) DeepCopy() *PlacementRef {
	if in == nil {
		return nil
	}
	out := new(PlacementRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RollingCanaryConfig) DeepCopyInto(out *RollingCanaryConfig) {
	*out = *in
	out.PlacementRef = in.PlacementRef
	if in.MaxConcurrentlyUpdating != nil {
		in, out := &in.MaxConcurrentlyUpdating, &out.MaxConcurrentlyUpdating
		*out = new(intstr.IntOrString)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RollingCanaryConfig.
func (in *RollingCanaryConfig) DeepCopy() *RollingCanaryConfig {
	if in == nil {
		return nil
	}
	out := new(RollingCanaryConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RollingConfig) DeepCopyInto(out *RollingConfig) {
	*out = *in
	if in.MaxConcurrentlyUpdating != nil {
		in, out := &in.MaxConcurrentlyUpdating, &out.MaxConcurrentlyUpdating
		*out = new(intstr.IntOrString)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RollingConfig.
func (in *RollingConfig) DeepCopy() *RollingConfig {
	if in == nil {
		return nil
	}
	out := new(RollingConfig)
	in.DeepCopyInto(out)
	return out
}
