package v1alpha1

// This file contains a collection of methods that can be used from go-restful to
// generate Swagger API documentation for its models. Please read this PR for more
// information on the implementation: https://github.com/emicklei/go-restful/pull/215
//
// TODOs are ignored from the parser (e.g. TODO(andronat):... || TODO:...) if and only if
// they are on one line! For multiple line or blocks that you want to ignore use ---.
// Any context after a --- is ignored.
//
// Those methods can be generated by using hack/update-swagger-docs.sh

// AUTO-GENERATED FUNCTIONS START HERE
var map_KlusterletVersion = map[string]string{
	"":       "KlusterletVersion is the configuration for the klusterlet version and upgrade strategy of selected managedClusters. This is where parameters related to automatic updates can be set.",
	"spec":   "Spec defines rolling upgrade strategy of the Klusterlets for the managed clusters.",
	"status": "Status represents the version status of the Klusterlets.",
}

func (KlusterletVersion) SwaggerDoc() map[string]string {
	return map_KlusterletVersion
}

var map_KlusterletVersionList = map[string]string{
	"":         "KlusterletVersionList is a list of KlusterletVersionList objects.",
	"metadata": "Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
	"items":    "List of KlusterletUpgradeStrategy objects.",
}

func (KlusterletVersionList) SwaggerDoc() map[string]string {
	return map_KlusterletVersionList
}

var map_KlusterletVersionSpec = map[string]string{
	"type":                "There are 2 types for klusterlet upgrade, Rolling and RollingCanary. The default is type is Rolling.",
	"rollingConfig":       "RollingConfig is the config for Rolling upgrade.",
	"rollingCanaryConfig": "RollingCanaryConfig is the config for RollingCanary upgrade.",
}

func (KlusterletVersionSpec) SwaggerDoc() map[string]string {
	return map_KlusterletVersionSpec
}

var map_KlusterletVersionStatus = map[string]string{
	"desiredVersion": "DesiredVersion is the MCE version.",
	"conditions":     "conditions describe the state of klusterlet upgrade.",
}

func (KlusterletVersionStatus) SwaggerDoc() map[string]string {
	return map_KlusterletVersionStatus
}

var map_PlacementRef = map[string]string{
	"name":      "Name of the placement",
	"namespace": "Namespace of the placement",
}

func (PlacementRef) SwaggerDoc() map[string]string {
	return map_PlacementRef
}

// AUTO-GENERATED FUNCTIONS END HERE
