package v1alpha1

// This file contains a collection of methods that can be used from go-restful to
// generate Swagger API documentation for its models. Please read this PR for more
// information on the implementation: https://github.com/emicklei/go-restful/pull/215
//
// TODOs are ignored from the parser (e.g. TODO(andronat):... || TODO:...) if and only if
// they are on one line! For multiple line or blocks that you want to ignore use ---.
// Any context after a --- is ignored.
//
// Those methods can be generated by using hack/update-swagger-docs.sh

// AUTO-GENERATED FUNCTIONS START HERE
var map_KlusterletConfig = map[string]string{
	"":       "KlusterletConfig contains the configuration of a klusterlet including the upgrade strategy, config overrides, proxy configurations etc.",
	"spec":   "Spec defines the desired state of KlusterletConfig",
	"status": "Status defines the observed state of KlusterletConfig",
}

func (KlusterletConfig) SwaggerDoc() map[string]string {
	return map_KlusterletConfig
}

var map_KlusterletConfigList = map[string]string{
	"": "KlusterletConfigList contains a list of KlusterletConfig.",
}

func (KlusterletConfigList) SwaggerDoc() map[string]string {
	return map_KlusterletConfigList
}

var map_KlusterletConfigSpec = map[string]string{
	"":              "KlusterletConfigSpec defines the desired state of KlusterletConfig, usually provided by the user.",
	"registries":    "Registries includes the mirror and source registries. The source registry will be replaced by the Mirror.",
	"pullSecret":    "PullSecret is the name of image pull secret.",
	"nodePlacement": "NodePlacement enables explicit control over the scheduling of the agent components. If the placement is nil, the placement is not specified, it will be omitted. If the placement is an empty object, the placement will match all nodes and tolerate nothing.",
}

func (KlusterletConfigSpec) SwaggerDoc() map[string]string {
	return map_KlusterletConfigSpec
}

var map_KlusterletConfigStatus = map[string]string{
	"": "KlusterletConfigStatus defines the observed state of KlusterletConfig.",
}

func (KlusterletConfigStatus) SwaggerDoc() map[string]string {
	return map_KlusterletConfigStatus
}

var map_Registries = map[string]string{
	"mirror": "Mirror is the mirrored registry of the Source. Will be ignored if Mirror is empty.",
	"source": "Source is the source registry. All image registries will be replaced by Mirror if Source is empty.",
}

func (Registries) SwaggerDoc() map[string]string {
	return map_Registries
}

// AUTO-GENERATED FUNCTIONS END HERE
