// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// UserPermissionListerExpansion allows custom methods to be added to
// UserPermissionLister.
type UserPermissionListerExpansion interface{}
