// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	clusterviewv1alpha1 "github.com/stolostron/cluster-lifecycle-api/clusterview/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// UserPermissionLister helps list UserPermissions.
// All objects returned here must be treated as read-only.
type UserPermissionLister interface {
	// List lists all UserPermissions in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*clusterviewv1alpha1.UserPermission, err error)
	// Get retrieves the UserPermission from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*clusterviewv1alpha1.UserPermission, error)
	UserPermissionListerExpansion
}

// userPermissionLister implements the UserPermissionLister interface.
type userPermissionLister struct {
	listers.ResourceIndexer[*clusterviewv1alpha1.UserPermission]
}

// NewUserPermissionLister returns a new UserPermissionLister.
func NewUserPermissionLister(indexer cache.Indexer) UserPermissionLister {
	return &userPermissionLister{listers.New[*clusterviewv1alpha1.UserPermission](indexer, clusterviewv1alpha1.Resource("userpermission"))}
}
