// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// BareMetalAssetListerExpansion allows custom methods to be added to
// BareMetalAssetLister.
type BareMetalAssetListerExpansion interface{}

// BareMetalAssetNamespaceListerExpansion allows custom methods to be added to
// BareMetalAssetNamespaceLister.
type BareMetalAssetNamespaceListerExpansion interface{}
