// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	"time"

	scheme "github.com/stolostron/cluster-lifecycle-api/client/view/clientset/versioned/scheme"
	v1beta1 "github.com/stolostron/cluster-lifecycle-api/view/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ManagedClusterViewsGetter has a method to return a ManagedClusterViewInterface.
// A group's client should implement this interface.
type ManagedClusterViewsGetter interface {
	ManagedClusterViews(namespace string) ManagedClusterViewInterface
}

// ManagedClusterViewInterface has methods to work with ManagedClusterView resources.
type ManagedClusterViewInterface interface {
	Create(ctx context.Context, managedClusterView *v1beta1.ManagedClusterView, opts v1.CreateOptions) (*v1beta1.ManagedClusterView, error)
	Update(ctx context.Context, managedClusterView *v1beta1.ManagedClusterView, opts v1.UpdateOptions) (*v1beta1.ManagedClusterView, error)
	UpdateStatus(ctx context.Context, managedClusterView *v1beta1.ManagedClusterView, opts v1.UpdateOptions) (*v1beta1.ManagedClusterView, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.ManagedClusterView, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.ManagedClusterViewList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.ManagedClusterView, err error)
	ManagedClusterViewExpansion
}

// managedClusterViews implements ManagedClusterViewInterface
type managedClusterViews struct {
	client rest.Interface
	ns     string
}

// newManagedClusterViews returns a ManagedClusterViews
func newManagedClusterViews(c *ViewV1beta1Client, namespace string) *managedClusterViews {
	return &managedClusterViews{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the managedClusterView, and returns the corresponding managedClusterView object, and an error if there is any.
func (c *managedClusterViews) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.ManagedClusterView, err error) {
	result = &v1beta1.ManagedClusterView{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("managedclusterviews").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ManagedClusterViews that match those selectors.
func (c *managedClusterViews) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.ManagedClusterViewList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.ManagedClusterViewList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("managedclusterviews").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested managedClusterViews.
func (c *managedClusterViews) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("managedclusterviews").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a managedClusterView and creates it.  Returns the server's representation of the managedClusterView, and an error, if there is any.
func (c *managedClusterViews) Create(ctx context.Context, managedClusterView *v1beta1.ManagedClusterView, opts v1.CreateOptions) (result *v1beta1.ManagedClusterView, err error) {
	result = &v1beta1.ManagedClusterView{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("managedclusterviews").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(managedClusterView).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a managedClusterView and updates it. Returns the server's representation of the managedClusterView, and an error, if there is any.
func (c *managedClusterViews) Update(ctx context.Context, managedClusterView *v1beta1.ManagedClusterView, opts v1.UpdateOptions) (result *v1beta1.ManagedClusterView, err error) {
	result = &v1beta1.ManagedClusterView{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("managedclusterviews").
		Name(managedClusterView.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(managedClusterView).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *managedClusterViews) UpdateStatus(ctx context.Context, managedClusterView *v1beta1.ManagedClusterView, opts v1.UpdateOptions) (result *v1beta1.ManagedClusterView, err error) {
	result = &v1beta1.ManagedClusterView{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("managedclusterviews").
		Name(managedClusterView.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(managedClusterView).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the managedClusterView and deletes it. Returns an error if one occurs.
func (c *managedClusterViews) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("managedclusterviews").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *managedClusterViews) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("managedclusterviews").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched managedClusterView.
func (c *managedClusterViews) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.ManagedClusterView, err error) {
	result = &v1beta1.ManagedClusterView{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("managedclusterviews").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
