// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/stolostron/cluster-lifecycle-api/client/inventory/clientset/versioned/typed/inventory/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeInventroyV1alpha1 struct {
	*testing.Fake
}

func (c *FakeInventroyV1alpha1) BareMetalAssets(namespace string) v1alpha1.BareMetalAssetInterface {
	return &FakeBareMetalAssets{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeInventroyV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
