// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/stolostron/cluster-lifecycle-api/inventory/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeBareMetalAssets implements BareMetalAssetInterface
type FakeBareMetalAssets struct {
	Fake *FakeInventroyV1alpha1
	ns   string
}

var baremetalassetsResource = schema.GroupVersionResource{Group: "inventroy.open-cluster-management.io", Version: "v1alpha1", Resource: "baremetalassets"}

var baremetalassetsKind = schema.GroupVersionKind{Group: "inventroy.open-cluster-management.io", Version: "v1alpha1", Kind: "BareMetalAsset"}

// Get takes name of the bareMetalAsset, and returns the corresponding bareMetalAsset object, and an error if there is any.
func (c *FakeBareMetalAssets) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.BareMetalAsset, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(baremetalassetsResource, c.ns, name), &v1alpha1.BareMetalAsset{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BareMetalAsset), err
}

// List takes label and field selectors, and returns the list of BareMetalAssets that match those selectors.
func (c *FakeBareMetalAssets) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.BareMetalAssetList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(baremetalassetsResource, baremetalassetsKind, c.ns, opts), &v1alpha1.BareMetalAssetList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.BareMetalAssetList{ListMeta: obj.(*v1alpha1.BareMetalAssetList).ListMeta}
	for _, item := range obj.(*v1alpha1.BareMetalAssetList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested bareMetalAssets.
func (c *FakeBareMetalAssets) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(baremetalassetsResource, c.ns, opts))

}

// Create takes the representation of a bareMetalAsset and creates it.  Returns the server's representation of the bareMetalAsset, and an error, if there is any.
func (c *FakeBareMetalAssets) Create(ctx context.Context, bareMetalAsset *v1alpha1.BareMetalAsset, opts v1.CreateOptions) (result *v1alpha1.BareMetalAsset, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(baremetalassetsResource, c.ns, bareMetalAsset), &v1alpha1.BareMetalAsset{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BareMetalAsset), err
}

// Update takes the representation of a bareMetalAsset and updates it. Returns the server's representation of the bareMetalAsset, and an error, if there is any.
func (c *FakeBareMetalAssets) Update(ctx context.Context, bareMetalAsset *v1alpha1.BareMetalAsset, opts v1.UpdateOptions) (result *v1alpha1.BareMetalAsset, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(baremetalassetsResource, c.ns, bareMetalAsset), &v1alpha1.BareMetalAsset{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BareMetalAsset), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeBareMetalAssets) UpdateStatus(ctx context.Context, bareMetalAsset *v1alpha1.BareMetalAsset, opts v1.UpdateOptions) (*v1alpha1.BareMetalAsset, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(baremetalassetsResource, "status", c.ns, bareMetalAsset), &v1alpha1.BareMetalAsset{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BareMetalAsset), err
}

// Delete takes name of the bareMetalAsset and deletes it. Returns an error if one occurs.
func (c *FakeBareMetalAssets) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(baremetalassetsResource, c.ns, name, opts), &v1alpha1.BareMetalAsset{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeBareMetalAssets) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(baremetalassetsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.BareMetalAssetList{})
	return err
}

// Patch applies the patch and returns the patched bareMetalAsset.
func (c *FakeBareMetalAssets) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.BareMetalAsset, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(baremetalassetsResource, c.ns, name, pt, data, subresources...), &v1alpha1.BareMetalAsset{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BareMetalAsset), err
}
