// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/stolostron/cluster-lifecycle-api/client/clusterview/clientset/versioned/typed/clusterview/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeClusterviewV1alpha1 struct {
	*testing.Fake
}

func (c *FakeClusterviewV1alpha1) UserPermissions() v1alpha1.UserPermissionInterface {
	return newFakeUserPermissions(c)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeClusterviewV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
