// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	clusterviewv1alpha1 "github.com/stolostron/cluster-lifecycle-api/client/clusterview/clientset/versioned/typed/clusterview/v1alpha1"
	v1alpha1 "github.com/stolostron/cluster-lifecycle-api/clusterview/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeUserPermissions implements UserPermissionInterface
type fakeUserPermissions struct {
	*gentype.FakeClientWithList[*v1alpha1.UserPermission, *v1alpha1.UserPermissionList]
	Fake *FakeClusterviewV1alpha1
}

func newFakeUserPermissions(fake *FakeClusterviewV1alpha1) clusterviewv1alpha1.UserPermissionInterface {
	return &fakeUserPermissions{
		gentype.NewFakeClientWithList[*v1alpha1.UserPermission, *v1alpha1.UserPermissionList](
			fake.Fake,
			"",
			v1alpha1.SchemeGroupVersion.WithResource("userpermissions"),
			v1alpha1.SchemeGroupVersion.WithKind("UserPermission"),
			func() *v1alpha1.UserPermission { return &v1alpha1.UserPermission{} },
			func() *v1alpha1.UserPermissionList { return &v1alpha1.UserPermissionList{} },
			func(dst, src *v1alpha1.UserPermissionList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.UserPermissionList) []*v1alpha1.UserPermission {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.UserPermissionList, items []*v1alpha1.UserPermission) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
