apiVersion: config.open-cluster-management.io/v1alpha1
kind: KlusterletVersion
metadata:
  name: version
spec:
  type: Rolling
  rollingConfig:
    maxConcurrentlyUpdating: 50%
status:
  desiredVersion: 2.3.1
  conditions:
    - lastTransitionTime: "2023-03-02T05:48:12Z"
      message: 20/60 upgrading...
      reason: Upgrading
      status: "False"
      type: Progressing


---
apiVersion: operator.open-cluster-management.io/v1
kind: Klusterlet
metadata:
  name: klusterlet
spec:
  clusterName: cluster1
 ...
status:
  version:
    klusterlet: 2.3.1