// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1beta1 "github.com/stolostron/cluster-lifecycle-api/view/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeManagedClusterViews implements ManagedClusterViewInterface
type FakeManagedClusterViews struct {
	Fake *FakeViewV1beta1
	ns   string
}

var managedclusterviewsResource = schema.GroupVersionResource{Group: "view.open-cluster-management.io", Version: "v1beta1", Resource: "managedclusterviews"}

var managedclusterviewsKind = schema.GroupVersionKind{Group: "view.open-cluster-management.io", Version: "v1beta1", Kind: "ManagedClusterView"}

// Get takes name of the managedClusterView, and returns the corresponding managedClusterView object, and an error if there is any.
func (c *FakeManagedClusterViews) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.ManagedClusterView, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(managedclusterviewsResource, c.ns, name), &v1beta1.ManagedClusterView{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ManagedClusterView), err
}

// List takes label and field selectors, and returns the list of ManagedClusterViews that match those selectors.
func (c *FakeManagedClusterViews) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.ManagedClusterViewList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(managedclusterviewsResource, managedclusterviewsKind, c.ns, opts), &v1beta1.ManagedClusterViewList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.ManagedClusterViewList{ListMeta: obj.(*v1beta1.ManagedClusterViewList).ListMeta}
	for _, item := range obj.(*v1beta1.ManagedClusterViewList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested managedClusterViews.
func (c *FakeManagedClusterViews) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(managedclusterviewsResource, c.ns, opts))

}

// Create takes the representation of a managedClusterView and creates it.  Returns the server's representation of the managedClusterView, and an error, if there is any.
func (c *FakeManagedClusterViews) Create(ctx context.Context, managedClusterView *v1beta1.ManagedClusterView, opts v1.CreateOptions) (result *v1beta1.ManagedClusterView, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(managedclusterviewsResource, c.ns, managedClusterView), &v1beta1.ManagedClusterView{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ManagedClusterView), err
}

// Update takes the representation of a managedClusterView and updates it. Returns the server's representation of the managedClusterView, and an error, if there is any.
func (c *FakeManagedClusterViews) Update(ctx context.Context, managedClusterView *v1beta1.ManagedClusterView, opts v1.UpdateOptions) (result *v1beta1.ManagedClusterView, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(managedclusterviewsResource, c.ns, managedClusterView), &v1beta1.ManagedClusterView{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ManagedClusterView), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeManagedClusterViews) UpdateStatus(ctx context.Context, managedClusterView *v1beta1.ManagedClusterView, opts v1.UpdateOptions) (*v1beta1.ManagedClusterView, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(managedclusterviewsResource, "status", c.ns, managedClusterView), &v1beta1.ManagedClusterView{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ManagedClusterView), err
}

// Delete takes name of the managedClusterView and deletes it. Returns an error if one occurs.
func (c *FakeManagedClusterViews) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(managedclusterviewsResource, c.ns, name, opts), &v1beta1.ManagedClusterView{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeManagedClusterViews) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(managedclusterviewsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta1.ManagedClusterViewList{})
	return err
}

// Patch applies the patch and returns the patched managedClusterView.
func (c *FakeManagedClusterViews) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.ManagedClusterView, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(managedclusterviewsResource, c.ns, name, pt, data, subresources...), &v1beta1.ManagedClusterView{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ManagedClusterView), err
}
