// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	"time"

	scheme "github.com/stolostron/cluster-lifecycle-api/client/clusterinfo/clientset/versioned/scheme"
	v1beta1 "github.com/stolostron/cluster-lifecycle-api/clusterinfo/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ManagedClusterInfosGetter has a method to return a ManagedClusterInfoInterface.
// A group's client should implement this interface.
type ManagedClusterInfosGetter interface {
	ManagedClusterInfos(namespace string) ManagedClusterInfoInterface
}

// ManagedClusterInfoInterface has methods to work with ManagedClusterInfo resources.
type ManagedClusterInfoInterface interface {
	Create(ctx context.Context, managedClusterInfo *v1beta1.ManagedClusterInfo, opts v1.CreateOptions) (*v1beta1.ManagedClusterInfo, error)
	Update(ctx context.Context, managedClusterInfo *v1beta1.ManagedClusterInfo, opts v1.UpdateOptions) (*v1beta1.ManagedClusterInfo, error)
	UpdateStatus(ctx context.Context, managedClusterInfo *v1beta1.ManagedClusterInfo, opts v1.UpdateOptions) (*v1beta1.ManagedClusterInfo, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.ManagedClusterInfo, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.ManagedClusterInfoList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.ManagedClusterInfo, err error)
	ManagedClusterInfoExpansion
}

// managedClusterInfos implements ManagedClusterInfoInterface
type managedClusterInfos struct {
	client rest.Interface
	ns     string
}

// newManagedClusterInfos returns a ManagedClusterInfos
func newManagedClusterInfos(c *InternalV1beta1Client, namespace string) *managedClusterInfos {
	return &managedClusterInfos{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the managedClusterInfo, and returns the corresponding managedClusterInfo object, and an error if there is any.
func (c *managedClusterInfos) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.ManagedClusterInfo, err error) {
	result = &v1beta1.ManagedClusterInfo{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("managedclusterinfos").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ManagedClusterInfos that match those selectors.
func (c *managedClusterInfos) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.ManagedClusterInfoList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.ManagedClusterInfoList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("managedclusterinfos").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested managedClusterInfos.
func (c *managedClusterInfos) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("managedclusterinfos").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a managedClusterInfo and creates it.  Returns the server's representation of the managedClusterInfo, and an error, if there is any.
func (c *managedClusterInfos) Create(ctx context.Context, managedClusterInfo *v1beta1.ManagedClusterInfo, opts v1.CreateOptions) (result *v1beta1.ManagedClusterInfo, err error) {
	result = &v1beta1.ManagedClusterInfo{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("managedclusterinfos").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(managedClusterInfo).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a managedClusterInfo and updates it. Returns the server's representation of the managedClusterInfo, and an error, if there is any.
func (c *managedClusterInfos) Update(ctx context.Context, managedClusterInfo *v1beta1.ManagedClusterInfo, opts v1.UpdateOptions) (result *v1beta1.ManagedClusterInfo, err error) {
	result = &v1beta1.ManagedClusterInfo{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("managedclusterinfos").
		Name(managedClusterInfo.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(managedClusterInfo).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *managedClusterInfos) UpdateStatus(ctx context.Context, managedClusterInfo *v1beta1.ManagedClusterInfo, opts v1.UpdateOptions) (result *v1beta1.ManagedClusterInfo, err error) {
	result = &v1beta1.ManagedClusterInfo{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("managedclusterinfos").
		Name(managedClusterInfo.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(managedClusterInfo).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the managedClusterInfo and deletes it. Returns an error if one occurs.
func (c *managedClusterInfos) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("managedclusterinfos").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *managedClusterInfos) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("managedclusterinfos").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched managedClusterInfo.
func (c *managedClusterInfos) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.ManagedClusterInfo, err error) {
	result = &v1beta1.ManagedClusterInfo{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("managedclusterinfos").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
