// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "github.com/stolostron/cluster-lifecycle-api/client/clusterview/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// UserPermissions returns a UserPermissionInformer.
	UserPermissions() UserPermissionInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// UserPermissions returns a UserPermissionInformer.
func (v *version) UserPermissions() UserPermissionInformer {
	return &userPermissionInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}
