// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	versioned "github.com/stolostron/cluster-lifecycle-api/client/clusterview/clientset/versioned"
	internalinterfaces "github.com/stolostron/cluster-lifecycle-api/client/clusterview/informers/externalversions/internalinterfaces"
	clusterviewv1alpha1 "github.com/stolostron/cluster-lifecycle-api/client/clusterview/listers/clusterview/v1alpha1"
	clusterlifecycleapiclusterviewv1alpha1 "github.com/stolostron/cluster-lifecycle-api/clusterview/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// UserPermissionInformer provides access to a shared informer and lister for
// UserPermissions.
type UserPermissionInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() clusterviewv1alpha1.UserPermissionLister
}

type userPermissionInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewUserPermissionInformer constructs a new informer for UserPermission type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewUserPermissionInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredUserPermissionInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredUserPermissionInformer constructs a new informer for UserPermission type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredUserPermissionInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ClusterviewV1alpha1().UserPermissions().List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ClusterviewV1alpha1().UserPermissions().Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ClusterviewV1alpha1().UserPermissions().List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ClusterviewV1alpha1().UserPermissions().Watch(ctx, options)
			},
		},
		&clusterlifecycleapiclusterviewv1alpha1.UserPermission{},
		resyncPeriod,
		indexers,
	)
}

func (f *userPermissionInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredUserPermissionInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *userPermissionInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&clusterlifecycleapiclusterviewv1alpha1.UserPermission{}, f.defaultInformer)
}

func (f *userPermissionInformer) Lister() clusterviewv1alpha1.UserPermissionLister {
	return clusterviewv1alpha1.NewUserPermissionLister(f.Informer().GetIndexer())
}
